### ISSUE TITLE
Candles data (BTC-USD/candles?granularity=60) does not match feed data

### ISSUE THREAD

**Issue by cnrudd** [coinbase/coinbase-pro-node#258]
Hi,

I would like to use the candles data obtained from https://api.gdax.com/products/BTC-USD/candles?granularity=60 to do some signal analysis, the most recent 350 intervals would be fine.

However, when I compare the data received from the candles endpoint with the data coming from the matches feed channel (aggregated into 1m candles), it doesn't seem to match.

See my attached screenshots which show the matches feed data in a redis console, the candles endpoint in postman, and the GDAX exchange GUI.

The matches feed data in my redis console and in the GDAX GUI are the same, but both differ considerably from the data received from the candles endpoint.

I would expect all of the interval entries to match across all three examples, but the candles endpoint seems to be off.

I was hoping to use the candles data to be able to generate some signal data without having to wait for 350 intervals to pass via feed collection, but if the candles endpoint is not reliable, this will not be possible.

Any insights would be appreciated.

Thank you!

![screen shot 2018-02-04 at 5 05 41 pm](https://user-images.githubusercontent.com/2573928/35782923-c3d33fea-09cd-11e8-8aaf-fd16e06fff74.png)

![screen shot 2018-02-04 at 5 21 33 pm](https://user-images.githubusercontent.com/2573928/35783084-ecfd3658-09cf-11e8-9456-8c0c2d3071fb.png)

**Comment by cnrudd** [comment]
Following up on this question, how am I to understand the discrepancy I see in the GDAX GUI 
where in the screenshot of the GUI at 5:22PM (1st screenshot) two recent intervals showed volume in excess of 100 BTC, but in the 2nd screenshot, the volume for those two intervals right before 5:22PM appears to have been reduced down to the teens.
![screen shot 2018-02-04 at 5 30 57 pm](https://user-images.githubusercontent.com/2573928/35783190-325a99f6-09d1-11e8-80bd-c023397f14d1.png)
![screen shot 2018-02-04 at 5 21 33 pm](https://user-images.githubusercontent.com/2573928/35783084-ecfd3658-09cf-11e8-9456-8c0c2d3071fb.png)

Is volume revised by some post interval cleanup process?

Thanks!

**Comment by scarboroughventures** [comment]
+1 for this

**Comment by ClimbsRocks** [comment]
I've seen something similar from the candles API- the volume figures in particular don't seem to line up to overall daily volume any longer (not just off-by-one errors, but consistently off by around a factor of 3).

**Comment by fb55** [comment]
The candles service is a bit unreliable right now, there is work being done to fix this.

**Comment by ClimbsRocks** [comment]
Any eta on that, even order of magnitude? Are we talking days, weeks, or quarters? I might have to shift to a different exchange 'til this is fixed.

The candles API is the only way to get historical data to train a model on, but it's tough doing algorithmic trading when the raw data at prediction time is mutable, and doesn't match up to the websocket.

Plus, it'll be fun to see those crazy big volume candles again- the current numbers just seem kinda puny and unimpressive compared to what the websocket says is happening :)

**Comment by cnrudd** [comment]
@fb55 
If candles produced by this endpoint /products/<product-id>/candles are unreliable, I guess we could use the paginated /products/<product-id>/trades endpoint to get trade data from the past and build our own past candles.

But to build a month's worth of 24hr interval candles would require thousands of calls to the /trades endpoint.

The GDAX docs do not warn against calling the /trades endpoint frequently (as it does for the /candles endpoint)  so, is it safe to assume that thousands of calls from one IP to the trades endpoint will not be ill received, as long as the calls respect the rate limit?

An IP address won't get blocked for hitting the trades endpoint 10800 times per hour?

**Comment by ClimbsRocks** [comment]
hmmmm, i tried doing this today and appear to have gotten blocked. i did some experimentation to see how long of a timeout i needed in between requests to stay within their rate limit. i did this maybe 5 times (continuous requests for 30-60 minutes) and then got blocked. i haven't been able to get anything from them in the nearly hour since then- even after taking a break for 10 or 30 minutes, i still get immediately 429'd on my first new request. 

so if you try this approach, i'd say be rather conservative in your requests. probably shoot for 2 requests per second, rather than 3. now i'm just trying to figure out how long this block stays in place...

**Comment by ClimbsRocks** [comment]
nvm, bug on my end caused the "blocked" behavior. looks like we're generally good to go with a lot of requests over time, as long as we respect the rate limits per second. 

from what i remember, rate limiting on gdax is one of the levers they pull to reduce traffic when they're swamped, so if you see some odd behavior here, it could just be because their servers are overwhelmed so they're being stricter about rate limiting.

**Comment by 7immer** [comment]
Any updates on this issue? I'm still getting un-reliable and fluctuating data?

https://runkit.com/jammer/5aa48476cf969b001299fb7b
(This link is showing different results per request)

**Comment by royitaqi** [comment]
Me, too. A simple example will be to paste the following URL into a browser and refresh for a few times, you will see that volume of some of the bars (even an old one) change by some chance.

https://api.gdax.com/products/BTC-USD/candles/?start=2018-03-30T00:00:00.000Z&end=2018-03-30T23:00:00.000Z&granularity=300

For example, at some refresh I see:

```
[1522425000,6721,6735,6721,6735,48.560780220000005]
```

and at some refresh I see:

```
[1522425000,6721,6735,6721,6735,46.99078022]
```

I think this is caused by data out of sync between gdax servers. Not sure what's your underlying infrastructure is.

**Comment by 7ammer** [comment]
@royitaqi this has been going on for months now and I've not heard anything from gdax :(

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
